# Generated by Django 6.0.6 on 2026-06-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorReview',
        ),
    ]
