# Generated by Django 6.0.6 on 2026-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_delete_doctorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
