# Generated by Django 6.0.6 on 2026-06-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_updated_at_doctoravailability_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['doctor', 'day', 'start_time'], 'verbose_name': 'Doctor Availability', 'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name'], 'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
    ]
